### PR TITLE
Small change - login -> username

### PR DESCRIPTION
**Pull request by lewiscowper**
Login describes what you want to do with that data, but in my opinion the username is what you actually want from the end user, and that's what the placeholder should reflect.

### CODE REVIEW

**Comment by andrew** [comment]
It was actually username when @briannelson added it, the only reason I changed it was the API response was login so it felt more natural to me, I don't mind either way.

**Comment by lewiscowper** [comment]
Ah fair enough, I should have checked the history. Feel free to close if it’s already been thought considered. :)

**Comment by andrew** [comment]
Any thoughts @briannelson?

**Comment by andrew** [comment]
Merged it in after asking a few other people offline, cheers!

**Comment by lewiscowper** [comment]
No worries. Keep up the good work. :+1:

**Pull request merged**
